name: build

on:
  push:
    branches:
      - main  # Adjust the branch name as needed
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Install dependencies
        run: |
          npm install
          cd backend
          npm install
          cd ../frontend
          npm install
      
      - name: Build project
        run: |
          cd frontend
          npm run build
